In [1]:
import numpy as np

In [2]:
# creation of numpy array
x = np.array([1,2,3,4,5])
print(x)
print(type(x)) # ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# shape and size
print(x.size) # total no. of elements
print(x.shape) # dimension wise elements
print(x.ndim) # num of dimensions

5
(5,)
1


In [6]:
x2d = np.array([[1,2,3],[4,5,6]])
print(x2d)
# shape and size
print(x2d.size) # total no. of elements
print(x2d.shape) # dimension wise elements
print(x2d.ndim) # num of dimensions

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [11]:
x25 = np.random.randint(1,100, (5,5))
print(x25)

[[10 16 64 48 14]
 [97 45 15 47 58]
 [55 30 20 34 32]
 [40 52 63 30 89]
 [15 92 64 67 57]]


In [21]:
xseq1 = np.arange(1, 101, 4)
print(xseq1.size,"elements")
print("=>1D MATRIX")
print(xseq1)
print("=>1D MATRIX RESHAPED TO 2D")
print(xseq1.reshape(5,5))

25 elements
=>1D MATRIX
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
=>1D MATRIX RESHAPED TO 2D
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [25]:
xseq2 = np.linspace(1, 100, 50)
print(xseq2.size,"elements")
print("=>1D MATRIX")
print(xseq2)
print("=>1D MATRIX RESHAPED TO 2D")
print(xseq2.reshape(10,5))
print("=>1D MATRIX RESHAPED TO 3D")
print(xseq2.reshape(5,5,2))

50 elements
=>1D MATRIX
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
=>1D MATRIX RESHAPED TO 2D
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  4

In [26]:
xseq2d = xseq2.reshape(10,5)
print(xseq2d)

[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.42857143  45.44897959  47.46938776  49.48979592]
 [ 51.51020408  53.53061224  55.55102041  57.57142857  59.59183673]
 [ 61.6122449   63.63265306  65.65306122  67.67346939  69.69387755]
 [ 71.71428571  73.73469388  75.75510204  77.7755102   79.79591837]
 [ 81.81632653  83.83673469  85.85714286  87.87755102  89.89795918]
 [ 91.91836735  93.93877551  95.95918367  97.97959184 100.        ]]


In [34]:
np.ones((5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- indexing and slicing
- boolean filter
- maths and stats
- methods

In [35]:
x25

array([[10, 16, 64, 48, 14],
       [97, 45, 15, 47, 58],
       [55, 30, 20, 34, 32],
       [40, 52, 63, 30, 89],
       [15, 92, 64, 67, 57]])

In [36]:
# first row
print(x25[0])

[10 16 64 48 14]


In [37]:
# last row
print(x25[-1])

[15 92 64 67 57]


In [38]:
# single element
print(x25[0,1]) # same as print(x25[0][1])

16


In [43]:
# 1st columns
print(x25[:, 0])

# 2nd columns
print(x25[:, 1])

# last columns
print(x25[:, -1])

[10 97 55 40 15]
[16 45 30 52 92]
[14 58 32 89 57]


In [44]:
# column 0 and 1 idxs
print(x25[:, [0,1]])

[[10 16]
 [97 45]
 [55 30]
 [40 52]
 [15 92]]


In [46]:
# column 0,1,2 idxs
print(x25[:, [0,1,2]])
# same thing as above
print(x25[:, :3])

[[10 16 64]
 [97 45 15]
 [55 30 20]
 [40 52 63]
 [15 92 64]]
[[10 16 64]
 [97 45 15]
 [55 30 20]
 [40 52 63]
 [15 92 64]]


In [50]:
# filtering data without numpy boolean filter (bad idea)
for i in x25:
    for j in i:
        if j <= 20:
            print(j)

10
16
14
15
20
15


In [51]:
x25 <= 20 # boolean filter

array([[ True,  True, False, False,  True],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [52]:
x25[ x25 <= 20 ]

array([10, 16, 14, 15, 20, 15])

In [53]:
x25[ x25 > 50 ]

array([64, 97, 58, 55, 52, 63, 89, 92, 64, 67, 57])

In [55]:
(x25 > 20) & (x25 < 70)

array([[False, False,  True,  True, False],
       [False,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False,  True,  True,  True]])

In [56]:
x25[(x25 > 20) & (x25 < 70)]

array([64, 48, 45, 47, 58, 55, 30, 34, 32, 40, 52, 63, 30, 64, 67, 57])

In [63]:
np.append(x25, [1,2,3,4,5]) # not as expected, but work

array([10, 16, 64, 48, 14, 97, 45, 15, 47, 58, 55, 30, 20, 34, 32, 40, 52,
       63, 30, 89, 15, 92, 64, 67, 57,  1,  2,  3,  4,  5])

In [74]:
np.append(x25, np.array([[1,2,3,5,6]]), axis=0) 

array([[10, 16, 64, 48, 14],
       [97, 45, 15, 47, 58],
       [55, 30, 20, 34, 32],
       [40, 52, 63, 30, 89],
       [15, 92, 64, 67, 57],
       [ 1,  2,  3,  5,  6]])

In [75]:
a = np.random.randint(1,100, (3,2))
b = np.random.randint(1,100, (2,3))

In [76]:
print(a.shape)
print(b.shape)

(3, 2)
(2, 3)


In [79]:
a.T # same as a.transpose()

array([[14, 43, 47],
       [76, 15, 47]])

In [85]:
print(np.hstack((a,b.T)))

[[14 76 56 77]
 [43 15 31 91]
 [47 47 83  8]]


In [84]:
print(np.hstack((a.T,b)))

[[14 43 47 56 31 83]
 [76 15 47 77 91  8]]


In [86]:
print(np.vstack((a,b.T)))
print(np.vstack((a.T,b)))

[[14 76]
 [43 15]
 [47 47]
 [56 77]
 [31 91]
 [83  8]]
[[14 43 47]
 [76 15 47]
 [56 31 83]
 [77 91  8]]
